ddsr:
  # Publish all joint states -----------------------------------
  wheel_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50.0

  # Drive wheels with differential drive controllers ---------------------------------------
  diff_drive_controller:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel: 'platform_2_left_wheel'
    right_wheel: 'platform_2_right_wheel'
    publish_rate: 50.0
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    twist_covariance_diagonal: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
    wheel_separation : 0.6
    wheel_radius : 0.1
    cmd_vel_timeout: 0.25
    base_frame_id: footprint
    enable_odom_tf: True
    velocity_rolling_window_size: 5

    # Velocity and acceleration limits (whenever a min_* is unspecified, default to -max_*)
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 1.0  # m/s
        has_acceleration_limits: true
        max_acceleration       : 1.5  # m/s^2
        has_jerk_limits        : true
        max_jerk               : 5.0  # m/s^3
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 2.0  # rad/s
        has_acceleration_limits: true
        max_acceleration       : 3.0  # rad/s^2
        has_jerk_limits        : true
        max_jerk               : 4.0  # rad/s^3

  # Caster wheel hinges ---------------------------------------
  caster_steer_controller:
    type: effort_controllers/JointEffortController
    joint: platform_2_caster_hinge_1

  # Caster wheel drive ---------------------------------------
  caster_drive_controller:
    type: effort_controllers/JointEffortController
    joint: caster_hinge_2_2_caster_wheel
