# Publish all joint states -----------------------------------
wheel_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50.0

# Drive wheels with differential drive controllers ---------------------------------------
diff_drive_controller:
    type        : "diff_drive_controller/DiffDriveController"
    left_wheel  : 'platform_2_left_wheel'
    right_wheel : 'platform_2_right_wheel'
    publish_rate: 50.0
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    twist_covariance_diagonal: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
    wheel_separation : 0.6
    wheel_radius : 0.1
    cmd_vel_timeout: 0.25
    base_frame_id: footprint
    enable_odom_tf: True
    velocity_rolling_window_size: 5

# Caster wheel hinges ---------------------------------------
caster_steer_controller:
    type: effort_controllers/JointEffortController
    joint: platform_2_caster_hinge_1

# Caster wheel drive ---------------------------------------
caster_drive_controller:
    type: effort_controllers/JointEffortController
    joint: caster_hinge_2_2_caster_wheel
